/**
 * 아티스트 한/영 교차 검색을 위한 별칭 매핑
 * 키와 값 모두 소문자로 저장하여 검색 시 대소문자 무시
 */
const aliasMap: Record<string, string[]> = {
  // 그룹
  "ive": ["아이브"],
  "아이브": ["ive"],
  "aespa": ["에스파"],
  "에스파": ["aespa"],
  "newjeans": ["뉴진스"],
  "뉴진스": ["newjeans"],
  "illit": ["아일릿"],
  "아일릿": ["illit"],
  "riize": ["라이즈"],
  "라이즈": ["riize"],
  "got7": ["갓세븐"],
  "갓세븐": ["got7"],
  "exo": ["엑소"],
  "엑소": ["exo"],
  "bts": ["방탄소년단", "방탄"],
  "방탄소년단": ["bts"],
  "방탄": ["bts"],
  "seventeen": ["세븐틴"],
  "세븐틴": ["seventeen"],
  "stray kids": ["스트레이키즈", "스키즈"],
  "스트레이키즈": ["stray kids"],
  "스키즈": ["stray kids"],
  "nct": ["엔시티"],
  "엔시티": ["nct"],
  "txt": ["투모로우바이투게더", "투바투"],
  "투모로우바이투게더": ["txt"],
  "투바투": ["txt"],
  "ateez": ["에이티즈"],
  "에이티즈": ["ateez"],
  "enhypen": ["엔하이픈"],
  "엔하이픈": ["enhypen"],
  "le sserafim": ["르세라핌"],
  "르세라핌": ["le sserafim"],
  "boynextdoor": ["보이넥스트도어"],
  "보이넥스트도어": ["boynextdoor"],
  "bss": ["부석순"],
  "부석순": ["bss"],
  "cnblue": ["씨엔블루"],
  "씨엔블루": ["cnblue"],
  "lngshot": ["롱샷"],
  "롱샷": ["lngshot"],
  "day6": ["데이식스"],
  "데이식스": ["day6"],
  "twice": ["트와이스"],
  "트와이스": ["twice"],
  "blackpink": ["블랙핑크"],
  "블랙핑크": ["blackpink"],
  "red velvet": ["레드벨벳"],
  "레드벨벳": ["red velvet"],
  "mamamoo": ["마마무"],
  "마마무": ["mamamoo"],
  "itzy": ["있지"],
  "있지": ["itzy"],
  "nmixx": ["엔믹스"],
  "엔믹스": ["nmixx"],
  "gidle": ["여자아이들", "(여자)아이들"],
  "(여자)아이들": ["gidle", "g-idle", "g idle"],
  "여자아이들": ["gidle", "g-idle"],
  "g-idle": ["여자아이들", "(여자)아이들"],
  "treasure": ["트레저"],
  "트레저": ["treasure"],
  "zerobaseone": ["제로베이스원", "zb1"],
  "제로베이스원": ["zerobaseone", "zb1"],
  "zb1": ["제로베이스원", "zerobaseone"],
  "babymonster": ["베이비몬스터"],
  "베이비몬스터": ["babymonster"],
  "kiss of life": ["키스오브라이프"],
  "키스오브라이프": ["kiss of life"],
  "qwer": ["쿼"],
  "쿼": ["qwer"],
  "bigbang": ["빅뱅"],
  "빅뱅": ["bigbang"],
  "shinee": ["샤이니"],
  "샤이니": ["shinee"],
  "winner": ["위너"],
  "위너": ["winner"],
  "ikon": ["아이콘"],
  "아이콘": ["ikon"],
  "btob": ["비투비"],
  "비투비": ["btob"],
  "astro": ["아스트로"],
  "아스트로": ["astro"],
  "monsta x": ["몬스타엑스"],
  "몬스타엑스": ["monsta x"],
  "the boyz": ["더보이즈"],
  "더보이즈": ["the boyz"],
  "viviz": ["비비지"],
  "비비지": ["viviz"],
  "weki meki": ["위키미키"],
  "위키미키": ["weki meki"],
  "brave girls": ["브레이브걸스"],
  "브레이브걸스": ["brave girls"],
  "브브걸": ["brave girls"],
  "girls generation": ["소녀시대", "snsd"],
  "소녀시대": ["girls generation", "snsd"],
  "snsd": ["소녀시대", "girls generation"],
  "wonder girls": ["원더걸스"],
  "원더걸스": ["wonder girls"],
  "2ne1": ["투애니원"],
  "투애니원": ["2ne1"],
  "super junior": ["슈퍼주니어", "슈주"],
  "슈퍼주니어": ["super junior"],
  "슈주": ["super junior"],

  // 솔로/기타
  "hynn": ["박혜원"],
  "박혜원": ["hynn"],
  "iu": ["아이유"],
  "아이유": ["iu"],
  "heize": ["헤이즈"],
  "헤이즈": ["heize"],
  "crush": ["크러쉬"],
  "크러쉬": ["crush"],
  "zico": ["지코"],
  "지코": ["zico"],
  "dean": ["딘"],
  "딘": ["dean"],
  "leehi": ["이하이"],
  "이하이": ["leehi", "lee hi"],
  "lee hi": ["이하이"],
  "jay park": ["박재범"],
  "박재범": ["jay park"],
  "rain": ["비", "정지훈"],
  "비": ["rain"],
  "psy": ["싸이"],
  "싸이": ["psy"],
  "taeyang": ["태양"],
  "태양": ["taeyang"],
  "gdragon": ["지드래곤", "g-dragon"],
  "지드래곤": ["gdragon", "g-dragon"],
  "g-dragon": ["지드래곤", "gdragon"],
  "sik-k": ["식케이"],
  "식케이": ["sik-k"],
  "lim kim": ["림킴"],
  "림킴": ["lim kim"],
  "paul kim": ["폴킴"],
  "폴킴": ["paul kim"],
  "kcm": ["케이씨엠"],
  "케이씨엠": ["kcm"],
  "giriboy": ["기리보이"],
  "기리보이": ["giriboy"],
  "verbal jint": ["버벌진트"],
  "버벌진트": ["verbal jint"],
  "young k": ["영케이"],
  "영케이": ["young k"],
  "d.o.": ["디오", "도경수"],
  "도경수": ["d.o.", "디오"],
  "디오": ["d.o.", "도경수"],
  "minnie": ["민니"],
  "민니": ["minnie"],
  "rosé": ["로제"],
  "로제": ["rosé", "rose"],
  "jennie": ["제니"],
  "제니": ["jennie"],
  "jisoo": ["지수"],
  "lisa": ["리사"],
  "리사": ["lisa"],
  "winter": ["윈터"],
  "윈터": ["winter"],
  "karina": ["카리나"],
  "카리나": ["karina"],
  "sulgi": ["슬기"],
  "슬기": ["sulgi", "seulgi"],
  "seulgi": ["슬기"],
  "youngposse": ["영파씨"],
  "영파씨": ["young posse"],
  "young posse": ["영파씨"],
  "han roro": ["한로로"],
  "한로로": ["han roro"],
};

/**
 * 검색어에 대한 모든 별칭을 반환합니다.
 * 예: "아일릿" → ["illit"]
 */
export function getAliases(query: string): string[] {
  const lower = query.toLowerCase().trim();
  return aliasMap[lower] || [];
}

/**
 * 원본 검색어 + 별칭을 모두 포함하여 검색 가능한 키워드 배열을 반환합니다.
 */
export function getSearchTerms(query: string): string[] {
  const lower = query.toLowerCase().trim();
  const aliases = aliasMap[lower] || [];
  return [lower, ...aliases];
}
