import { Song } from "./types";

export const memberInfo = {
  "1": { name: "1", avatar: "/assets/member-1.png" },
  "2": { name: "2", avatar: "/assets/member-2.png" },
  "3": { name: "3", avatar: "/assets/member-3.png" },
};

export const mockSongs: Song[] = [
  {
    id: "1",
    title: "Supernova",
    artist: "aespa",
    album: "Armageddon",
    rating: 3.8,
    memberRatings: [
      { memberId: "1", rating: 4.0, comment: "중독성 있는 멜로디가 인상적" },
      { memberId: "2", rating: 3.5, comment: "실험적이지만 호불호 갈릴 듯" },
      { memberId: "3", rating: 4.0, comment: "aespa만의 색깔이 뚜렷하다" },
    ],
    reviewer: "익평삼",
    reviewText: "중독성 있는 멜로디와 실험적인 사운드가 잘 어우러진 곡. aespa만의 색깔이 뚜렷하다.",
    genre: "K-Pop",
    coverUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop",
    createdAt: "2024-06-01",
    isOfficial: true,
    subscriberRating: 4.1,
  },
  {
    id: "2",
    title: "해요 (HAYO)",
    artist: "IU",
    album: "The Winning",
    rating: 4.0,
    memberRatings: [
      { memberId: "1", rating: 4.5, comment: "IU 보컬의 진가를 보여준 곡" },
      { memberId: "2", rating: 3.5, comment: "깔끔하지만 임팩트가 아쉽다" },
      { memberId: "3", rating: 4.0, comment: "감성적인 가사가 좋다" },
    ],
    reviewer: "익평삼",
    reviewText: "IU의 보컬이 돋보이는 곡. 감성적인 가사와 깔끔한 프로듀싱이 인상적이다.",
    genre: "K-Pop / Ballad",
    coverUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=300&h=300&fit=crop",
    createdAt: "2024-05-15",
    isOfficial: true,
    subscriberRating: 4.2,
  },
  {
    id: "3",
    title: "SPOT!",
    artist: "ZICO (feat. JENNIE)",
    album: "Single",
    rating: 3.3,
    memberRatings: [
      { memberId: "1", rating: 3.5, comment: "재치 있는 가사가 포인트" },
      { memberId: "2", rating: 3.0, comment: "대중적이지만 깊이가 아쉽다" },
      { memberId: "3", rating: 3.5, comment: "가볍게 듣기 좋은 곡" },
    ],
    reviewer: "익평삼",
    reviewText: "대중적인 어필은 확실하지만 음악적 깊이는 아쉬운 편. 재치 있는 가사가 포인트.",
    genre: "K-Pop / Hip-Hop",
    coverUrl: "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=300&h=300&fit=crop",
    createdAt: "2024-04-28",
    isOfficial: true,
    subscriberRating: 3.5,
  },
  {
    id: "4",
    title: "Welcome to the Show",
    artist: "DAY6",
    album: "Fourever",
    rating: 4.5,
    memberRatings: [
      { memberId: "1", rating: 5.0, comment: "라이브로 들으면 소름 돋는 명곡" },
      { memberId: "2", rating: 4.0, comment: "밴드 사운드의 정수" },
      { memberId: "3", rating: 4.5, comment: "DAY6의 절정기를 보여준 곡" },
    ],
    reviewer: "익평삼",
    reviewText: "DAY6의 밴드 사운드가 절정에 달한 곡. 라이브로 들으면 소름이 돋을 명곡.",
    genre: "K-Rock / Band",
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&h=300&fit=crop",
    createdAt: "2024-04-10",
    isOfficial: true,
    subscriberRating: 4.5,
  },
  {
    id: "5",
    title: "Magnetic",
    artist: "ILLIT",
    album: "SUPER REAL ME",
    rating: 3.5,
    memberRatings: [
      { memberId: "1", rating: 3.5, comment: "신인답지 않은 완성도" },
      { memberId: "2", rating: 3.0, comment: "하이브 프로듀싱이 느껴진다" },
      { memberId: "3", rating: 4.0, comment: "중독성 있는 곡" },
    ],
    reviewer: "익평삼",
    reviewText: "신인답지 않은 완성도. 하이브의 프로듀싱 파워가 느껴지는 곡.",
    genre: "K-Pop",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop",
    createdAt: "2024-03-25",
    isOfficial: true,
    subscriberRating: 3.8,
  },
  {
    id: "6",
    title: "Ditto",
    artist: "NewJeans",
    album: "OMG",
    rating: 4.8,
    memberRatings: [
      { memberId: "1", rating: 5.0, comment: "완벽에 가까운 팝 송" },
      { memberId: "2", rating: 4.5, comment: "K-Pop의 흐름을 바꾼 곡" },
      { memberId: "3", rating: 5.0, comment: "올해의 곡이라 할 만하다" },
    ],
    reviewer: "익평삼",
    reviewText: "2020년대 K-Pop의 흐름을 바꾼 곡이라 해도 과언이 아니다. 완벽에 가까운 팝 송.",
    genre: "K-Pop",
    coverUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=300&h=300&fit=crop",
    createdAt: "2024-03-10",
    isOfficial: true,
    subscriberRating: 4.7,
  },
];

export const mockUserReviews: Song[] = [
  {
    id: "u1",
    title: "APT.",
    artist: "ROSÉ & Bruno Mars",
    rating: 4.3,
    reviewer: "음악팬123",
    reviewText: "글로벌 감성과 K-Pop의 완벽한 조화!",
    genre: "Pop",
    coverUrl: "https://images.unsplash.com/photo-1484755560615-a4c64e778571?w=300&h=300&fit=crop",
    createdAt: "2024-11-20",
    isOfficial: false,
  },
];
